name: 📺 Channel Request
description: Request to add a channel into the database
title: 'Add: '
labels: ['channel request']

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the issue template as much as you can so we could efficiently process your request

  - type: input
    attributes:
      label: Channel Name
      description: Official channel name in English
      placeholder: 'Anhui TV'
    validations:
      required: true

  - type: input
    attributes:
      label: Native Name (optional)
      description: Channel name in the original language. Used when different from `name`. May contain any characters except `,` and `"`
      placeholder: '安徽卫视'

  - type: input
    attributes:
      label: Network (optional)
      description: Network of which this channel is a part.
      placeholder: 'Anhui'

  - type: input
    attributes:
      label: Country
      description: Country code from which the channel is transmitted. A list of all supported countries and their codes can be found in [data/countries.csv](data/countries.csv) 
      placeholder: 'CN'
    validations:
      required: true

  - type: input
    attributes:
      label: Subdivision (optional)
      description: Code of the subdivision (e.g., provinces or states) from which the broadcast is transmitted. A list of all supported subdivisions and their codes can be found in [data/subdivisions.csv](data/subdivisions.csv)
      placeholder: 'CN-AH'

  - type: input
    attributes:
      label: City (optional)
      description: Name of the city from which the channel is transmitted
      placeholder: 'Hefei'

  - type: input
    attributes:
      label: Broadcast Area
      description: List of codes describing the broadcasting area of the channel. Any combination of `r/<region_code>`, `c/<country_code>`, `s/<subdivision_code>`
      placeholder: 's/CN-AH'
    validations:
      required: true

  - type: input
    attributes:
      label: Languages
      description: List of languages in which the channel is broadcast separated by `;`. A list of all supported languages and their codes can be found in [data/languages.csv](data/languages.csv)
      placeholder: 'zho;eng'
    validations:
      required: true

  - type: input
    attributes:
      label: Categories (optional)
      description: List of categories to which this channel belongs separated by `;`. A list of all supported categories can be found in [data/categories.csv](data/categories.csv)
      placeholder: 'animation;kids'

  - type: input
    attributes:
      label: NSFW
      description: Indicates whether the channel broadcasts adult content
      options:
        - label: 'FALSE'
        - label: 'TRUE'
    validations:
      required: true

  - type: input
    attributes:
      label: Launched (optional)
      description: Launch date of the channel (`YYYY-MM-DD`)   
      placeholder: '2016-07-28'

  - type: input
    attributes:
      label: Closed (optional)
      description: Date on which the channel closed (`YYYY-MM-DD`)   
      placeholder: '2020-05-31'

  - type: input
    attributes:
      label: Replaced By (optional)
      description: The ID of the channel that this channel was replaced by
      placeholder: 'CCTV1.cn'

  - type: input
    attributes:
      label: Website (optional)
      description: Official website URL
      placeholder: 'http://www.ahtv.cn/'

  - type: input
    attributes:
      label: Logo
      description: Logo URL
      placeholder: 'https://example.com/logo.png'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Notes
      description: 'Anything else we should know about this channel?'
